name: Docs Deploy to GitHub Pages
on: [workflow_dispatch]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"
          registry-url: "https://registry.npmjs.org"

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn typedoc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
